services:
  redis:
    image: redis
    volumes:
      - ./docker/redis:/usr/local/etc/redis
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      timeout: 20s
      retries: 10

  influxdb:
    image: influxdb
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb2
      - ./docker/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: wilson
      DOCKER_INFLUXDB_INIT_PASSWORD: 123456123456
      DOCKER_INFLUXDB_INIT_ORG: my-org
      DOCKER_INFLUXDB_INIT_BUCKET: websocket_server
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-influxdb-auth-token
    healthcheck:
      test: [ "CMD", "curl", "influxdb:8086/api/v2/ping" ]
      interval: 1m
      timeout: 10s
      retries: 5

  websocket_server:
    build:
      context: .
      dockerfile: deploy/api/linux/Dockerfile
#      dockerfile: deploy/api/windows/Dockerfile
    environment:
      CONN_INFLUXDB_HOST: influxdb
      CONN_INFLUXDB_ORG: my-org
      CONN_INFLUXDB_TOKEN: my-super-influxdb-auth-token
      CONN_INFLUXDB_BUCKET: websocket_server
      CONN_REDIS_HOST: redis
      CONN_REDIS_PORT: 6379
      CONN_REDIS_IS_CLUSTER: False
      CONN_REDIS_DB: 15

    ports:
      - 5488:5488
    volumes:
      - ./docker/log:/app/log
    depends_on:
      redis:
        condition: service_healthy
      influxdb:
        condition: service_healthy
